apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  # Note that unlike most provider configs this one supports an array of
  # credentials. This is because each Terraform workspace uses a single
  # Crossplane provider config, but could use multiple Terraform providers each
  # with their own credentials.
  credentials:
    - filename: gcp-credentials.json
      source: Secret
      secretRef:
        namespace: crossplane
        name: tf-gcp-creds
        key: credentials
    - filename: .git-credentials
      source: Secret
      secretRef:
        namespace: crossplane
        name: git-credentials
        key: .git-credentials
  # This optional configuration block can be used to inject HCL into any
  # workspace that uses this provider config, for example to setup Terraform
  # providers.
  configuration: |
    provider "google" {
      credentials = "gcp-credentials.json"
      project     = "linear-skill-384413"
      region      = "us-central1"
    }

    // Modules _must_ use remote state. The provider does not persist state.
    terraform {
      backend "gcs" {
        bucket = "masudalabs-crossplane-backends"
        prefix = "terraform/state"
        credentials = "gcp-credentials.json"
      }
    }

